CREATE TABLE Event
(
    Id UNIQUEIDENTIFIER NOT NULL,
    BotId UNIQUEIDENTIFIER NOT NULL,
    BotType NVARCHAR(50) NOT NULL,
    EventType NVARCHAR(50) NOT NULL,
    ActionType NVARCHAR(50) NOT NULL,
    EnergyBegin DECIMAL(17,2) NOT NULL,
    EnergyEnd DECIMAL(17,2) NULL,
    Status NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NULL,
    CONSTRAINT PK_Event PRIMARY KEY (Id)
)
GO

CREATE NONCLUSTERED INDEX IX_Event_BotId ON Event(BotId)
GO

CREATE NONCLUSTERED INDEX IX_Event_BotId_Status ON Event(BotId, Status)
GO
