CREATE TABLE Event
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    BotId INT NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Action NVARCHAR(50) NOT NULL,
    EnergyChange INT NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL
)
GO

CREATE NONCLUSTERED INDEX IX_Event_BotId ON Event(BotId)
GO
