DROP INDEX IX_Event_BotId ON Event
GO

ALTER TABLE [Event] DROP COLUMN BotId;
GO 

ALTER TABLE [Event]
ADD BotId UNIQUEIDENTIFIER NOT NULL;
GO

CREATE NONCLUSTERED INDEX IX_Event_BotId ON Event(BotId)
GO
